name: CICD

env:
  repository: jannemattila/unnecessary-roughness
  image: 1.1.${{ github.run_number }}
  context: .
  dockerfile: src/UR.Server/Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_hub_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          file: ${{ env.dockerfile }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.repository }}:latest
            ${{ env.repository }}:${{ env.image }}

      - name: Login to Azure
        uses: azure/login
        if: github.event_name == 'push'
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 

      - run: |
          az containerapp update --name ur --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --image ${{ env.repository }}:${{ env.image }} -o none
        if: github.event_name == 'push'

      - name: Digest
        run: echo ${{ steps.docker_hub_build.outputs.digest }}
